name: 构建并发布 Android APK

on:
  push:
    branches:
      - main  # 替换为您希望触发工作流程的分支名称

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 授予 gradlew 执行权限
        run: chmod +x gradlew

      - name: 使用 Gradle 构建
        run: ./gradlew build

      - name: 构建调试 APK
        run: ./gradlew assembleDebug --stacktrace

      - name: 创建发布
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.sha }}  # 使用提交 SHA 作为唯一标识
          release_name: Debug APK - ${{ github.sha }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 上传调试 APK 到发布
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Android-Doc-QA_${{ github.sha }}_debug.apk
          asset_content_type: application/vnd.android.package-archive