名称：构建并发布 Android APK

在：
  推：
    标签：
      -‘v * ’​

工作：
  构建apk文件：
    运行于：ubuntu-latest
    步骤：
      -用途：actions/checkout@v3
        和：
          子模块：' true '

      -名称：设置 JDK 17
        用途：actions/setup-java@v3
        和：
          Java 版本：' 17 '
          分布：' temurin '
          缓存：gradle

      -名称：解码密钥库
        环境：
          编码字符串：${{ secrets.KEYSTORE_BASE_64 }}
          发布密钥密码：${{ secrets.发布密钥密码 }}
          发布密钥对：${{ secrets.发布密钥对}}
          发布密钥密码：${{ secrets.发布密钥密码 }}
        运行：|
          回显 $ENCODED_STRING> keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
      - name :授予 gradlew 执行权限
        运行：chmod +x gradlew

      -名称：使用 Gradle 构建
        环境：
          发布密钥密码：${{ secrets.发布密钥密码 }}
          发布密钥对：${{ secrets.发布密钥对}}
          发布密钥密码：${{ secrets.发布密钥密码 }}
        运行：./gradlew build

      -名称：构建APK
        环境：
          发布密钥密码：${{ secrets.发布密钥密码 }}
          发布密钥对：${{ secrets.发布密钥对}}
          发布密钥密码：${{ secrets.发布密钥密码 }}
        运行：./gradlew assembleRelease --stacktrace

      -名称：创建发布
        用途：actions/create-release@v1
        id：create_release
        和：
          标签名称：${{ github.ref }}
          发布名称：${{ github.ref }}
          草稿：false
          预发布：false
          body_path : CHANGELOG.md
        环境：
          GITHUB_TOKEN：${{ github.token }}

      -名称：上传APK以发布
        用途：actions/upload-release-asset@v1
        环境：
          GITHUB_TOKEN：${{ github.token }}
        和：
          上传网址：${{ steps.create_release.outputs.upload_url }}
          asset_path：app/build/outputs/apk/release/app-release.apk
          资产名称：Android-Doc-QA_${{ github.ref_name }}.apk
          asset_content_type：应用程序/vnd.android.package-archive
