 
name: 构建并发布 Android APK

on:
  push:
    branches:
      - main  # 替换为您的分支名称

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 授予 gradlew 执行权限
        run: chmod +x gradlew

      - name: 使用 Gradle 构建
        run: ./gradlew build

      - name: 构建调试 APK
        run: ./gradlew assembleDebug --stacktrace

      - name: 上传 APK 到 Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug  # Artifact 名称
          path: app/build/outputs/apk/debug/app-debug.apk  # APK 路径
 